-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 10:28:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lab1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lab1` ;

-- -----------------------------------------------------
-- Table `lab1`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`course` (
  `CourseID` INT NOT NULL,
  `CourseName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`CourseID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`department` (
  `DepartmentID` INT NOT NULL,
  `DepartmentName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`DepartmentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`lecturer` (
  `LecturerID` INT NOT NULL,
  `LecturerName` VARCHAR(255) NULL DEFAULT NULL,
  `DepartmentID` INT NOT NULL,
  PRIMARY KEY (`LecturerID`, `DepartmentID`),
  INDEX `fk_Lecturer_Department1_idx` (`DepartmentID` ASC) VISIBLE,
  CONSTRAINT `fk_Lecturer_Department1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `lab1`.`department` (`DepartmentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`student` (
  `StudentID` VARCHAR(255) NOT NULL,
  `StudentName` VARCHAR(255) NULL DEFAULT NULL,
  `Major` VARCHAR(255) NULL DEFAULT NULL,
  `DoB` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`register` (
  `course_CourseID` INT NOT NULL,
  `student_StudentID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`course_CourseID`, `student_StudentID`),
  INDEX `fk_course_has_student_student1_idx` (`student_StudentID` ASC) VISIBLE,
  INDEX `fk_course_has_student_course_idx` (`course_CourseID` ASC) VISIBLE,
  CONSTRAINT `fk_course_has_student_course`
    FOREIGN KEY (`course_CourseID`)
    REFERENCES `lab1`.`course` (`CourseID`),
  CONSTRAINT `fk_course_has_student_student1`
    FOREIGN KEY (`student_StudentID`)
    REFERENCES `lab1`.`student` (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab1`.`teach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1`.`teach` (
  `Course_CourseID` INT NOT NULL,
  `Lecturer_LecturerID` INT NOT NULL,
  PRIMARY KEY (`Course_CourseID`, `Lecturer_LecturerID`),
  INDEX `fk_Course_has_Lecturer_Lecturer1_idx` (`Lecturer_LecturerID` ASC) VISIBLE,
  INDEX `fk_Course_has_Lecturer_Course1_idx` (`Course_CourseID` ASC) VISIBLE,
  CONSTRAINT `fk_Course_has_Lecturer_Course1`
    FOREIGN KEY (`Course_CourseID`)
    REFERENCES `lab1`.`course` (`CourseID`),
  CONSTRAINT `fk_Course_has_Lecturer_Lecturer1`
    FOREIGN KEY (`Lecturer_LecturerID`)
    REFERENCES `lab1`.`lecturer` (`LecturerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
